version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    #image: pms-docker-bnowakowski
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 33400:33400
      - 33443:33443
    environment:
      - TZ=Europe/Warsaw
      - PLEX_CLAIM=claim-qNyz28ZHdXKv2YsaZdvN
      - ADVERTISE_IP=http://164.132.42.164:32400/
      - PLEX_UID=1003
      - PLEX_GID=1000
    hostname: ovh.bnowakowski.pl
    volumes:
      - ./data/config:/config
      - ./data/transcode:/transcode
      - ./data/data:/data
    privileged: true
